### ISSUE TITLE
Ability to query GitLab API which is accessible by http rather than https

### ISSUE THREAD

**Issue by jzaldokas** [phillipj/gitlab-search#11]
Our privately hosted GitLab instance is accessible only with http://gitlab_domain/api/v4 but gitlab-search always uses https:// prefix when constructing URL. Would be nice if this could be configurable or overridden when `--api-domain` option includes protocol as well, i.e,
`gitlab-search setup mytoken --api-domain http://my_git_domain`.

**Comment by phillipj** [comment]
Hi there!

Surely makes sense to allow HTTP when needed. I like your suggestion about using an already related argument, instead of creating yet another argument..

Although it may end up being a little misleading that `--api-domain` can actually include the scheme as well, renaming it is a bit painful since the same name is used in `.gitlabsearchrc` files. I'm okey with starting with `--api-domain` and consider renaming it if get lots of questions from confused users.

**Comment by phillipj** [comment]
Hi again @jzaldokas!

After having tried a few different approaches to allowing HTTP requests being sent instead of HTTPS, I've published a beta version where `--api-domain` works as you initially suggested (in PR #13).

Any chance you're able to give it a test run to see if it works as you would expect? 🤞 

```
$ npm install -g gitlab-search@1.1.0-beta1
```

..followed by running the `gitlab-search setup` command again, pretty much as you described yourself back in February.

**Comment by phillipj** [comment]
@jzaldokas any chance you've got the opportunity to give the suggested changes a spin?

**Comment by jzaldokas** [comment]
Hi @phillipj
Sorry to get back to his so late. Yes, I've just tried the beta version and gitlab-search over our HTTP API works perfectly.

Thank you for introducing this option and for this useful tool!

**Comment by phillipj** [comment]
Yeay great to hear and thanks for testing, much appreciated! I'll get to
push a released version ASAP.

**Comment by phillipj** [comment]
Closing as v1.1.0 just got published to npm which allows HTTP be used as you requested.

Thanks for contributing with the suggestion and testing 👍
